runtime: nodejs18

# App Engine Standard environment configuration
env: standard

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

# Environment variables (override with gcloud app deploy --env-vars-file)
env_variables:
  NODE_ENV: 'production'

# Handlers for static files and routing
handlers:
  # Service worker - no cache
  - url: /service-worker.js
    static_files: dist/service-worker.js
    upload: dist/service-worker.js
    http_headers:
      Cache-Control: 'no-cache, no-store, must-revalidate'
      Pragma: 'no-cache'
      Expires: '0'

  # Static assets with caching
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$
    http_headers:
      Cache-Control: 'public, max-age=31536000, immutable'

  # PWA manifest
  - url: /manifest.json
    static_files: dist/manifest.json
    upload: dist/manifest.json
    http_headers:
      Cache-Control: 'public, max-age=86400'

  # All other routes - serve index.html (SPA routing)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    http_headers:
      Cache-Control: 'no-cache'

# Security headers
includes:
  - url: /.*
    http_headers:
      X-Frame-Options: 'DENY'
      X-Content-Type-Options: 'nosniff'
      X-XSS-Protection: '1; mode=block'
      Referrer-Policy: 'strict-origin-when-cross-origin'
